CrowdFunding/CrowdFunding/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import activate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pro/', include('projects.urls')),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('verification/', include('verify_email.urls')),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',  
        activate, name='activate'), 
]

CrowdFunding/accounts/urls.py
from django.urls import path
from . import views
from accounts.views import signup
from django.contrib.auth import views as auth_views
app_name="accounts"
urlpatterns = [
    path('', signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(),name="logout"),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),name="login"),
    path('profile/', views.profile , name="profile" ), 
    path('edit/', views.edit , name="edit" ),
    path('delete/', views.delete , name="delete" ),
    path('add/', views.add , name="add" ),
]

CrowdFunding/home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home),
]

CrowdFunding/projects/urls.py
from django.urls import path
from projects import views

app_name = 'projects'

urlpatterns = [
    path('add/', views.AddProjects.as_view()),
    path('', views.ViewProjects.as_view()),
    path('proapi/', views.ProjectsApi.as_view()),
    path('loginapi/', views.LoginApi.as_view()),
    path('project/<id>', views.Project.as_view(), name='project'),
    path('donate/', views.Donate.as_view(), name='donate'),
    path('comment/', views.Comment.as_view(), name='comment'),
    path('reply/', views.Reply.as_view(), name='reply'),
    path('cancel/', views.Cancel.as_view(), name='cancel'),
    path('report/<typ>/<id>', views.Report.as_view(), name='report'),
]

CrowdFunding/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.aggregates import Max


class Reg(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone = models.IntegerField()
    profile = models.ImageField(upload_to='static/accounts/images/')
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50)
    password = models.CharField(max_length=80)


class Userinfo (models.Model) :
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    birth= models.DateField(),
    country = models.CharField(max_length=100),
    facebook_profile =  models.CharField(max_length=100)

CrowdFunding/home/models.py
from django.db import models

# Create your models here.

CrowdFunding/accounts/forms.py
from django import forms
from django.contrib.auth import forms as myforms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import widgets


class SignupForm (UserCreationForm) :
    email = forms.EmailField(required=True)
    phone = forms.IntegerField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    

    
    
 

CrowdFunding/accounts/views.py
from django.shortcuts import redirect, render 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from projects.models import Projects, ProjectRating
from accounts.models import User, Userinfo, Reg

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login as auth_login

from verify_email.email_handler import send_verification_email

from django.http import HttpResponse  
from django.shortcuts import render, redirect  
from django.contrib.auth import login, authenticate, get_user_model
from .forms import SignupForm  
from django.contrib.sites.shortcuts import get_current_site  
from django.utils.encoding import force_bytes, force_text  
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode  
from django.template.loader import render_to_string  
from .token import account_activation_token  
from django.contrib.auth.models import User  
from django.core.mail import EmailMessage  


# def sign(request):
#     if request.user.is_authenticated:
#         return redirect('/pro')
#     form = signupForm()
#     if request.method == "POST":
#         form = signupForm(request.POST)
#         if form.is_valid():
#             user=form.save()
#             Reg.objects.create(user=user, phone=request.POST["phone"], profile=request.FILES.get("pic"), fname=request.POST['first_name'], lname=request.POST['last_name'], password=request.POST['password1'])
#             auth_login(request, user)
#             return redirect('/pro')
#     return render(request, 'accounts/signup.html', {'form': form})

def signup(request):  
    if request.method == 'POST':  
        form = SignupForm(request.POST)  
        if form.is_valid():  
            # save form in the memory not in database  
            user = form.save(commit=False)  
            user.is_active = False  
            user.save()
            Reg.objects.create(user=user, phone=request.POST["phone"], profile=request.FILES.get("pic"), fname=request.POST['first_name'], lname=request.POST['last_name'], password=request.POST['password1'])
            # to get the domain of the current site  
            current_site = get_current_site(request)  
            mail_subject = 'Activation link has been sent to your email id'  
            message = render_to_string('acc_active_email.html', {  
                'user': user,  
                'domain': current_site.domain,  
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),  
                'token':account_activation_token.make_token(user),  
            })  
            to_email = form.cleaned_data.get('email')  
            email = EmailMessage(  
                        mail_subject, message, to=[to_email]  
            )  
            email.send()  
            return HttpResponse('Please confirm your email address to complete the registration')  
    else:  
        form = SignupForm()  
    return render(request, 'accounts/signup.html', {'form': form})   


def activate(request, uidb64, token):  
    User = get_user_model()  
    try:  
        uid = force_text(urlsafe_base64_decode(uidb64))  
        user = User.objects.get(pk=uid)  
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):  
        user = None  
    if user is not None and account_activation_token.check_token(user, token):  
        user.is_active = True  
        user.save()  
        # return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
        return redirect("/accounts/login")
    else:  
        return HttpResponse('Activation link is invalid!')  
  


@login_required
def profile (request) :
    if request.user.is_authenticated:
        User = request.user 
        UserId= request.user.id 
        profile=Reg.objects.get(user_id=UserId)
        UserProjects=Projects.objects.filter(user=UserId).all()
        UserDonations=ProjectRating.objects.filter(user=UserId).all()
        return render(request, 'accounts/profile.html',{"user":User , "UserProjects":UserProjects , "donations" :  UserDonations ,"profile":profile})
    else:
        return redirect("/accounts/login")



@login_required
def edit(request):
    if request.method == "POST":
        User = request.user 
        if request.POST['fname']:
            Reg.objects.filter(user=User).update(fname=request.POST['fname'])
        if request.POST['lname']:
            Reg.objects.filter(user=User).update(lname=request.POST['lname'])
        if request.POST['phone']:
            Reg.objects.filter(user=User).update(phone=request.POST['phone'])
        if request.FILES['image']:
            reg = Reg.objects.get(user=User)
            Reg.objects.create(user=request.user, phone=reg.phone, profile=request.FILES.get("image"), fname=reg.fname, lname=reg.lname)
            reg.delete()
    return redirect("/accounts/profile")
   
@login_required
def delete (request) :
    UserId= request.user.id
    if  request.POST["password1"] == Reg.objects.get(user=UserId).password:
        User.objects.filter(id=UserId).delete()
        return redirect("/accounts/logout")
    else:
        wrongpassword = "password is not confirmed"
        return render(request, 'accounts/profile.html',{"wrongpassword" : wrongpassword })
 

@login_required
def add (request) :
    print(request.POST)
    Userinfo.objects.create(user=request.user,birth=request.POST["birthday"],country=request.POST["country"],facebook_profile=request.POST["facebookprofile"])
    return redirect("/accounts/profile")
     
      
        
        
        
        
                                                  

 

CrowdFunding/home/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect
from projects.models import ProjectRating ,Projects ,ProjectTags
from django.contrib.auth.decorators import login_required


@login_required
def home(request):
    if (request.method == 'GET'):

        a=ProjectRating.objects.all().order_by('-rating')[:5]
        b = Projects.objects.all().order_by('-created')[:5]
        c = Projects.objects.filter(featured=True).order_by('-created')[:5]
        d = Projects.objects.filter(user=request.user)
        return render(request,'home/index.html',{"a": a ,"b":b ,"c":c ,"d":d})
    else:
        search = request.POST['search']
        l = []
        for a in Projects.objects.all():
            l.append(a.title)
        ltag = []
        for a in ProjectTags.objects.all():
            ltag.append(a.tag)
        resultTile = list(filter(lambda project: search.lower() in project.lower(), l))
        resultTag = list(filter(lambda project: search.lower() in project.lower(), ltag))
        print(resultTag)
        ids = []

        for i in resultTile:
            ids.append(Projects.objects.get(title=i))
        for i in resultTag:
            ids.append(ProjectTags.objects.get(tag=i).project)
        a = ProjectRating.objects.all().order_by('-rating')[:5]
        b = Projects.objects.all().order_by('-created')[:5]
        c = Projects.objects.filter(featured=True).order_by('-created')[:5]
        d = Projects.objects.filter(user=request.user)
        ids = list(dict.fromkeys(ids))
        return render(request, 'home/index.html', {"a": a, "b": b, "c": c, "d": d, "ids": ids})

CrowdFunding/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        
    <title>{% block title %} Document {% endblock %} </title>
  
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

CrowdFunding/templates/accounts/home.html
{% extends 'accounts/base.html' %}


{%block title %}
home
{% endblock %}

{%block body%}
<div class="container">
 <h1> welcome{{user.username}} </h1>
</div>
{% endblock%}

CrowdFunding/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{%block title %}
signup
{% endblock %}

{%block body%}
<div class="container">
    <form method="post" novalidate>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{next}}">
        {% include 'accounts/includes/form.html' %}
        <br>
        <br>
        <button class="btn btn-primary" type="submit"> login </button>
        <div>
            don't have an account ? <a href="{%url 'accounts:signup' %}">sign up</a>
        </div>
    </form>
</div>
{% endblock%}

CrowdFunding/templates/accounts/profile.html
{% extends 'base.html' %} 

{% block sidebar %}
<div style="display: inline-block; float: left; text-align: center; padding: auto;">
 <img src="{{profile.profile.url}}" style="width: 400px;">
 <h1> {{profile.fname}} {{profile.lname}} </h1>
</div>

{% endblock %}

{% block style %}
<script>
  const deleter = () => {
    p1 = document.getElementById('pass1').value
    p2 = document.getElementById('pass2').value
    if (p1 == p2){
      document.getElementById('delform').submit()
    } else{
      alert('password is not matching confirm password')
    }
}
</script>
{% endblock %}

import  {test.js}  from {'/static/js'}
{% load static %}
 {% block profile %}active{% endblock %}
 {% block title %}{{ profile.fname }}'s profile{% endblock %}
 {%block body%}
<style>
    button {
        height: 50px;
        width: 200px;
    }
     #myprojects , #mydonations , #edit ,#additinal{
        
         text-align: center;
         margin: auto;
         margin-top: 100px; 
         display: none;   
     }
    
</style>


<div id="main">
<button id="one" class= "btn btn-primary mt-5"> my projects </button>
<button id="three" class= "btn btn-primary mt-5">  my donations </button>
<button id="two" class= "btn btn-primary mt-5">edit </button>
<button id="four" class= "btn btn-primary mt-5" > additional </button>
<button id="five" class= "btn btn-danger mt-5" > Delete Acount </button>

</div>

<div id="myprojects" >
    <h1>your projects are : </h1>
     <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Category</th>
        <th scope="col">Total Target</th>
        <th scope="col">Start Date</th>
        <th scope="col">End Date</th>


      </tr>
    </thead>
    <tbody> 
        {%for project in UserProjects%}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td> <a href="{% url 'projects:project' project.id %}">{{ project.title }}</a></td>
          <td>{{ project.category }}</td>
          <td>{{ project.totalTarget }}</td>
          <td>{{ project.start }}</td>
          <td>{{ project.end }}</td>
        </tr>
      {% endfor %} 
    </tbody>
     </table>
   </div>


   <div id="mydonations" >
    <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">project</th>
        <th scope="col">donations</th>
      </tr>
    </thead>
     <tbody> 
      {%for  donation in  donations%} 
     <tr>
    <td> {{donation.project.title}}</td>
    <td>{{donation.donations}}</td>
     </tr>
     {%endfor%}
    </tbody>
  </table>

</div> 


<div id="edit" > 
 
  <form action="{%url 'accounts:edit'%}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label" > First name </label>
    <input type="text" class="form-control" name="fname">
  </div>

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label" > Last name </label>
    <input type="text" class="form-control" name="lname">
  </div>

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label" > Phone </label>
    <input type="number" class="form-control" name="phone">
  </div>


  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label" > Profile Picture </label>
    <input name="image" type="file" accept="image/*">
  </div>


  <button type="submit" class="btn btn-primary">Edit</button>

</form>

</div>

<div id="additinal">  

 <form action="{%url 'accounts:add'%}" method="POST" >
      {% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label" > birth_day </label>
    <input type="date" class="form-control" name="birthday">

  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label" > country</label>
    <input type="text" class="form-control" id="exampleInputPassword1" name="country">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label" >facebook_profile</label>
    <input type="text" class="form-control" id="exampleInputPassword1" name="facebookprofile">
  </div>
  
  <button type="submit" class="btn btn-primary">submit</button>
</form>



</div>


<div id="delete">
  <form id="delform" action="{% url 'accounts:delete'%}" method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label" > Enter Password</label>
      <input type="password" class="form-control" id="pass1" name="password1">
    </div>

    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label" >Confirm Password</label>
      <input type="password" class="form-control" id="pass2" name="password2">
    </div>

    <h5>{{wrongpassword}}</h5>
    <button class="btn btn-danger" type="button" onclick="deleter()">Delete</button>
  </form>
</div>

 

     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
     <script src="/static/js/test.js"></script>
    {%endblock%}

CrowdFunding/templates/accounts/signup.html
{% extends 'accounts/base.html' %}
   
 {%block title %}
  signup
 {% endblock %}

{%block body%}
<div class="container">
    <form method="post" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'accounts/includes/form.html' %}
        <br>
        <label>Profile Picture:</label>
        <input type="file" name="pic"  accept="image/*">
        <br>
        <br>
        <button class="btn btn-primary" type="submit" > create an account </button>
    </form>
    <div>
        already have an account ? <a href="{%url 'accounts:login' %}">log in</a>
    </div>
</div>
{% endblock%}